### PR TITLE
Fix error message for large index inputs and update github specifications in user guide

### LINKED ISSUE #136: [PE-D] Wrong output message for delete command
Steps to reproduce:
1. Follow the command shown in the picture.

Wrong output message. As per the user guide, as long as INDEX is a positive integer, the command should work. But it gave an incorrect command format. Should it be invalid index instead?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tandeshao/ped#20

### PR DESCRIPTION
**Pull request by LowJiaHao99**
resolves #136 and #106

### CODE REVIEW

File: src/test/java/seedu/address/commons/util/StringUtilTest.java [hunk 1]
```diff
@@ -16,33 +16,36 @@
...
-        assertFalse(StringUtil.isNonZeroUnsignedInteger("1 0")); // Spaces in the middle
+        assertFalse(StringUtil.isNonZeroSignedIntegerLessThanIntegerLimit(" 10 ")); // Leading/trailing spaces
+        assertFalse(StringUtil.isNonZeroSignedIntegerLessThanIntegerLimit("1 0")); // Spaces in the middle
 
         // EP: number larger than Integer.MAX_VALUE
-        assertFalse(StringUtil.isNonZeroUnsignedInteger(Long.toString(Integer.MAX_VALUE + 1)));
+        assertFalse(StringUtil.isNonZeroSignedIntegerLessThanIntegerLimit(Long.toString(Integer.MAX_VALUE + 1)));
+
+        // EP: number larger than Integer.MAX_VALUE
+        assertTrue(StringUtil.isNonZeroSignedIntegerLessThanIntegerLimit(Long.toString(Integer.MAX_VALUE)));
```
Comment (jaysmyname) [inline src/test/java/seedu/address/commons/util/StringUtilTest.java:44]: Change incorrect EP comment

**Review by jaysmyname — COMMENTED** [review]
Looks all good except for one inaccurate comment
