### PR TITLE
addtg will not relist now

### LINKED ISSUE #146: [PE-D] Editing tutorial group would wipe all existing tutorial group records for that student
Feature tested: edit

Steps to reproduce:

add n/John Doe tg/CS2100 G08 e/e0123456@u.nus.edu

addtg 5 tg/CS2101 T01

edit 5 tg/CS2101 T02

Issue: Does not allow for editing of individual tutorial groups, instead wipes all records of tutorial groups for the student. Though this is noted in the User Guide, legitimate user behaviour is not handled when a student is assigned to more than 1 tutorial group

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jinnhl/ped#8

### PR DESCRIPTION
**Pull request by hqhqhq1**
Resolves #146

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -82,7 +84,20 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setStudent(studentToEdit, editedStudent);
-        model.updateFilteredStudentList(PREDICATE_SHOW_ALL_STUDENTS);
+
+        //keep the current list of filtered student and edited student
+        if (!model.getFilteredStudentList().equals(model.getSortedStudentList())) {
+            FilteredList<Student> test = (FilteredList<Student>) model.getFilteredStudentList();
+            @SuppressWarnings("unchecked")
+            //test.getPredicate() must be a Predicate<Student> type
```
Comment (LowJiaHao99) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:92]: will an assertion statement that test.getPredicate() is an instance of Predicate<Student> work?

**Review by LowJiaHao99 — CHANGES_REQUESTED** [review]
Only 1 small change required, otherwise LGTM.

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -82,7 +84,20 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setStudent(studentToEdit, editedStudent);
-        model.updateFilteredStudentList(PREDICATE_SHOW_ALL_STUDENTS);
+
+        //keep the current list of filtered student and edited student
+        if (!model.getFilteredStudentList().equals(model.getSortedStudentList())) {
+            FilteredList<Student> test = (FilteredList<Student>) model.getFilteredStudentList();
```
Comment (LowJiaHao99) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:90]: `test` may not be intuitive. Perhaps `modelFilteredList` is beter?

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 3]
```diff
@@ -82,7 +84,20 @@ public CommandResult execute(Model model) throws CommandException {
...
+            @SuppressWarnings("unchecked")
+            //test.getPredicate() must be a Predicate<Student> type
+            Predicate<Student> predicateTest = (Predicate<Student>) test.getPredicate();
```
Comment (LowJiaHao99) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:93]: Does `modelFilteredListPredicate` sound better?

**Review by LowJiaHao99 — CHANGES_REQUESTED** [review]
Some code quality improvement required. Once resolved LGTM

**Review by LowJiaHao99 — APPROVED** [review]

**Comment by LowJiaHao99** [comment]
LGTM
